-- =============================================================================
-- GuitarPro Seed Data — 100 Songs (50 Hindi + 50 English)
-- =============================================================================

-- HINDI SONGS (1-50)
INSERT INTO songs (title,artist,language,difficulty,guitar_type,bpm,thumbnail) VALUES
('Tum Hi Ho','Arijit Singh','Hindi','Beginner','Acoustic',72,'🎵'),
('Kal Ho Na Ho','Sonu Nigam','Hindi','Intermediate','Acoustic',80,'🎸'),
('Ae Dil Hai Mushkil','Arijit Singh','Hindi','Beginner','Acoustic',68,'🎵'),
('Channa Mereya','Arijit Singh','Hindi','Intermediate','Acoustic',76,'🎸'),
('Raabta','Arijit Singh','Hindi','Beginner','Acoustic',64,'🎵'),
('Phir Le Aya Dil','Arijit Singh','Hindi','Advanced','Acoustic',85,'🎸'),
('Kabira','Rekha Bhardwaj','Hindi','Beginner','Acoustic',78,'🎵'),
('Sooraj Dooba Hain','Arijit Singh','Hindi','Intermediate','Electric',88,'⚡'),
('Gerua','Arijit Singh','Hindi','Advanced','Acoustic',92,'🎸'),
('Tere Sang Yaara','Atif Aslam','Hindi','Beginner','Acoustic',70,'🎵'),
('Mann Bharrya','B Praak','Hindi','Intermediate','Acoustic',75,'🎸'),
('Kesariya','Arijit Singh','Hindi','Beginner','Acoustic',84,'🎵'),
('Dooba Dooba','Silk Route','Hindi','Intermediate','Electric',90,'⚡'),
('Iktara','Amitabh Bhattacharya','Hindi','Beginner','Acoustic',66,'🎵'),
('Jeena Jeena','Atif Aslam','Hindi','Beginner','Acoustic',72,'🎸'),
('Saware','Arijit Singh','Hindi','Advanced','Acoustic',82,'🎵'),
('Teri Meri','Rahat Fateh Ali','Hindi','Beginner','Acoustic',68,'🎸'),
('Dil Dhadakne Do','Arijit Singh','Hindi','Intermediate','Acoustic',86,'🎵'),
('Bulleya','Amit Mishra','Hindi','Advanced','Electric',94,'⚡'),
('Janam Janam','Arijit Singh','Hindi','Beginner','Acoustic',74,'🎵'),
('Zindagi Na Milegi Dobara','Shankar Ehsaan Loy','Hindi','Intermediate','Acoustic',80,'🎸'),
('Hawayein','Arijit Singh','Hindi','Beginner','Acoustic',76,'🎵'),
('Kalank','Arijit Singh','Hindi','Advanced','Acoustic',88,'🎸'),
('Woh Ladki','Kishor Kumar','Hindi','Beginner','Acoustic',70,'🎵'),
('Mere Naam Tu','Abhay Jodhpurkar','Hindi','Intermediate','Acoustic',78,'🎸'),
('Khairiyat','Arijit Singh','Hindi','Beginner','Acoustic',72,'🎵'),
('Bekhayali','Sachet Tandon','Hindi','Advanced','Electric',96,'⚡'),
('Pachtaoge','Arijit Singh','Hindi','Intermediate','Acoustic',82,'🎸'),
('Aithey Aa','Akasa Singh','Hindi','Beginner','Acoustic',74,'🎵'),
('Lut Gaye','Jubin Nautiyal','Hindi','Intermediate','Acoustic',80,'🎸'),
('Roja','AR Rahman','Hindi','Intermediate','Acoustic',78,'🎵'),
('Agar Tum Saath Ho','Arijit Singh','Hindi','Beginner','Acoustic',66,'🎸'),
('Mast Magan','Arijit Singh','Hindi','Beginner','Acoustic',76,'🎵'),
('Tujh Mein Rab Dikhta Hai','Roop Kumar Rathod','Hindi','Intermediate','Acoustic',72,'🎸'),
('Yeh Tune Kya Kiya','Zeb and Haniya','Hindi','Beginner','Acoustic',70,'🎵'),
('Enna Sona','Arijit Singh','Hindi','Beginner','Acoustic',74,'🎸'),
('Tere Bina','AR Rahman','Hindi','Advanced','Acoustic',84,'🎵'),
('Galliyan','Ankit Tiwari','Hindi','Intermediate','Acoustic',80,'🎸'),
('Ilahi','Arijit Singh','Hindi','Beginner','Acoustic',68,'🎵'),
('Banjaara','Mohammad Irfan','Hindi','Beginner','Acoustic',76,'🎸'),
('Main Phir Bhi Tumko Chahhunga','Arijit Singh','Hindi','Intermediate','Acoustic',78,'🎵'),
('Meherbaan','Arijit Singh','Hindi','Advanced','Electric',90,'⚡'),
('Tu Hi Haqeeqat','Javed Ali','Hindi','Beginner','Acoustic',72,'🎸'),
('Ae Watan','Arijit Singh','Hindi','Intermediate','Acoustic',84,'🎵'),
('Hasi','Ami Mishra','Hindi','Beginner','Acoustic',70,'🎸'),
('Ek Villain Title','Mustafa Zahid','Hindi','Intermediate','Electric',88,'⚡'),
('Chahun Main Ya Naa','Arijit Singh','Hindi','Beginner','Acoustic',74,'🎵'),
('Phir Mohabbat','Arijit Singh','Hindi','Intermediate','Acoustic',78,'🎸'),
('Meri Aashiqui','Jubin Nautiyal','Hindi','Beginner','Acoustic',72,'🎵'),
('Baarish','Atif Aslam','Hindi','Beginner','Acoustic',76,'🎸');

-- ENGLISH SONGS (51-100)
INSERT INTO songs (title,artist,language,difficulty,guitar_type,bpm,thumbnail) VALUES
('Hotel California','Eagles','English','Advanced','Electric',75,'⚡'),
('Wonderwall','Oasis','English','Beginner','Acoustic',87,'🎸'),
('Knockin on Heavens Door','Bob Dylan','English','Beginner','Acoustic',72,'🎵'),
('Nothing Else Matters','Metallica','English','Advanced','Electric',68,'⚡'),
('Let Her Go','Passenger','English','Beginner','Acoustic',96,'🎸'),
('Wish You Were Here','Pink Floyd','English','Intermediate','Acoustic',66,'🎵'),
('Sweet Home Alabama','Lynyrd Skynyrd','English','Intermediate','Electric',97,'⚡'),
('Stairway to Heaven','Led Zeppelin','English','Advanced','Acoustic',82,'🎸'),
('Shape of You','Ed Sheeran','English','Beginner','Acoustic',96,'🎵'),
('Smoke on the Water','Deep Purple','English','Beginner','Electric',112,'⚡'),
('Tears in Heaven','Eric Clapton','English','Intermediate','Acoustic',80,'🎸'),
('More Than Words','Extreme','English','Intermediate','Acoustic',72,'🎵'),
('Zombie','The Cranberries','English','Beginner','Electric',85,'⚡'),
('Fast Car','Tracy Chapman','English','Beginner','Acoustic',100,'🎸'),
('Free Fallin','Tom Petty','English','Beginner','Acoustic',86,'🎵'),
('Come As You Are','Nirvana','English','Intermediate','Electric',120,'⚡'),
('Behind Blue Eyes','The Who','English','Intermediate','Acoustic',72,'🎸'),
('House of the Rising Sun','The Animals','English','Intermediate','Acoustic',76,'🎵'),
('Here Comes the Sun','The Beatles','English','Intermediate','Acoustic',130,'🎸'),
('Blackbird','The Beatles','English','Advanced','Acoustic',96,'🎵'),
('Creep','Radiohead','English','Beginner','Electric',92,'⚡'),
('Country Roads','John Denver','English','Beginner','Acoustic',80,'🎸'),
('Jolene','Dolly Parton','English','Beginner','Acoustic',164,'🎵'),
('Purple Rain','Prince','English','Advanced','Electric',58,'⚡'),
('Hallelujah','Leonard Cohen','English','Intermediate','Acoustic',58,'🎸'),
('Brown Eyed Girl','Van Morrison','English','Beginner','Acoustic',148,'🎵'),
('Hey There Delilah','Plain White Ts','English','Beginner','Acoustic',90,'🎸'),
('With or Without You','U2','English','Beginner','Electric',113,'⚡'),
('Losing My Religion','REM','English','Intermediate','Acoustic',131,'🎸'),
('Stand By Me','Ben E King','English','Beginner','Acoustic',119,'🎵'),
('Aint No Sunshine','Bill Withers','English','Intermediate','Acoustic',76,'🎸'),
('Dust in the Wind','Kansas','English','Intermediate','Acoustic',96,'🎵'),
('Mad World','Tears for Fears','English','Beginner','Acoustic',88,'🎸'),
('The Sound of Silence','Simon Garfunkel','English','Intermediate','Acoustic',96,'🎵'),
('Clocks','Coldplay','English','Intermediate','Electric',131,'⚡'),
('Yellow','Coldplay','English','Beginner','Acoustic',88,'🎸'),
('The Scientist','Coldplay','English','Beginner','Acoustic',75,'🎵'),
('Californication','RHCP','English','Intermediate','Electric',96,'⚡'),
('Under the Bridge','RHCP','English','Intermediate','Electric',72,'⚡'),
('Fix You','Coldplay','English','Beginner','Acoustic',70,'🎸'),
('Every Rose Has a Thorn','Poison','English','Beginner','Acoustic',108,'🎵'),
('Love of My Life','Queen','English','Advanced','Acoustic',76,'🎸'),
('Sultans of Swing','Dire Straits','English','Advanced','Electric',146,'⚡'),
('Hurt','Johnny Cash','English','Beginner','Acoustic',44,'🎵'),
('When the Partys Over','Billie Eilish','English','Beginner','Acoustic',86,'🎸'),
('Perfect','Ed Sheeran','English','Beginner','Acoustic',95,'🎵'),
('Photograph','Ed Sheeran','English','Beginner','Acoustic',107,'🎸'),
('Stay With Me','Sam Smith','English','Beginner','Acoustic',84,'🎵'),
('Shallow','Lady Gaga','English','Intermediate','Acoustic',96,'🎸'),
('Bohemian Rhapsody','Queen','English','Advanced','Electric',72,'⚡');

-- Sample tutorials for first 5 songs
INSERT INTO tutorials (song_id, tabs, chords, strumming_pattern, tips) VALUES
(1, 'e|--0---0---0---0---|\nB|--1---1---1---1---|\nG|--2---2---0---0---|\nD|--2---2---2---2---|\nA|--0---0---3---3---|\nE|------------------|\n(Am --- F --- C --- G)', '["Am","F","C","G"]', 'D DU UDU', '["Start slow at 50% tempo","Focus on clean Am to F transition","Keep strumming wrist loose"]'),
(2, 'e|--3---3---0---0---|\nB|--0---0---0---0---|\nG|--0---0---0---0---|\nD|--0---0---2---2---|\nA|--2---2---2---2---|\nE|--3---3---0---0---|\n(G --- Em --- C --- D)', '["G","Em","C","D"]', 'D D DU UDU', '["Use capo 3 for original key","Practice G to Em change daily","Count beats out loud initially"]'),
(3, 'e|--3---3---2---2---|\nB|--3---3---3---3---|\nG|--0---0---2---2---|\nD|--0---0---0---0---|\nA|--2---2-----------|\nE|--3---3---0---0---|\n(G --- D --- Am --- C)', '["G","D","Am","C"]', 'D DU DU', '["Only 4 chords - perfect beginner song","Bob Dylan simplified version","Focus on rhythm over speed"]'),
(4, 'e|--0---0---0---0---|\nB|--0---0---1---1---|\nG|--1---1---0---0---|\nD|--2---2---2---2---|\nA|--2---2---3---3---|\nE|--0---0-----------|\n(Em --- D --- C --- G)', '["Em","D","C","G"]', 'D DU D DU', '["The intro is fingerpicked - master it first","Very slow ballad - control is key","End solo requires patience to learn"]'),
(5, 'e|--0---2---3---3---|\nB|--1---3---3---1---|\nG|--0---2---0---0---|\nD|--2---0---0---2---|\nA|--3-----------3---|\nE|-----------3------|\n(C --- D --- G --- Am)', '["C","G","Am","F"]', 'DU DU DU DU', '["Capo 5 for original key","Classic beginner song","Focus on clean chord changes"]');
